module.exports = {
  AMAZON_S3_KEY: process.env.AMAZON_S3_KEY,
  AMAZON_S3_SECRET: process.env.AMAZON_S3_SECRET,
  AMAZON_S3_IMGBUCKETNAME: process.env.AMAZON_S3_IMGBUCKETNAME,
  AMAZON_S3_AUDIOBUCKETNAME: process.env.AMAZON_S3_AUDIOBUCKETNAME,
  UPLOAD_IMG_FIELD: 'images',
  UPLOAD_AUDIO_FIELD: 'audio'
};
